# both docker_image_build and docker_service_deploy need access, so these aren't in role/vars

# hosts that aren't docker_build_images get empty role_volumes
role_volumes: []
common_volumes: []
host_volumes: []
volumes: "{{ role_volumes + common_volumes + host_volumes }}"
