# test copying a directory structure
type: copy
src: "hosts/{{ inventory_hostname }}/files/test_copy_directory"
dest: "/root"

# modes are passed to the file and copy modules, so multiple formats are valid
directory_mode: "0700"
mode: "u=rw,g=,o="

# test configuration, not part of ansible role
_test_config:
  paths:
    # all copie paths, files *and* directories
    # add trailing slashes to directories for readability
    - /root/copied_file
    - /root/anotherlayer/
    - /root/anotherlayer/copied_file
  # for convenience all files are the same content
  # NOTE there is a newline in the source file
  file_contents: "This file was copied.\n"
  # mode must be specified as a string representation of an octal integer for testing
  directory_mode: "0700"
  mode: "0600"
