# test templating a directory structure
type: template
src: "hosts/{{ inventory_hostname }}/templates/basic_test"
dest: "/root"

# modes are passed to the file and template modules, so multiple formats are valid
directory_mode: "0700"
mode: "u=rw,g=,o="

# test configuration, not part of ansible role
_test_config:
  paths:
    # all templated paths, files *and* directories
    # add trailing slashes to directories for readability
    - /root/basic_template
    - /root/anotherlayer/
    - /root/anotherlayer/basic_template
  # for convenience all files are the same template
  # we effectively test templating once
  # but also test that the recursion works as expected
  # NOTE there is a newline in the template file
  file_contents: "This file was templated for template-directory.\n"
  # mode must be specified as a string representation of an octal integer for testing
  directory_mode: "0700"
  mode: "0600"
