- name: create staging paths
  file:
    path: "{{ docker_build_directory.path }}/{{ item.key }}"
    state: directory
  loop: "{{ staging_paths | dict2items }}"
  when: "not ('is_base_path' in item.value and item.value.is_base_path)"

- include_role:
    name: stage_items
  vars:
    # stage items into our created temp path
    dest: "{{ docker_build_directory.path }}"
