- hosts: docker_services
  # playbooks gather facts before roles, which is where delegation is performed
  # so set gather_facts to no here, and run setup explicitly in the role
  gather_facts: no
  roles:
    - role: gather_facts
      delegate_to: "{{ groups['docker_build_hosts'] | first }}"

    - role: docker_service_build
      delegate_to: "{{ groups['docker_build_hosts'] | first }}"
      when: "'build' in tags"
      production_image: yes

    - role: docker_service_build
      delegate_to: "{{ groups['docker_build_hosts'] | first }}"
      when: "'build' in tags"
      production_image: no
