- hosts: docker_build_images
  # playbooks gather facts before roles, which is where delegation is performed
  # so set gather_facts to no here, and run setup explicitly in the role
  gather_facts: no
  roles:
    - role: docker_skip_hosts_in_registry
      delegate_to: "{{ groups['docker_build_hosts'] | first }}"
      tags:
        - never
        - skip-if-in-registry

    - role: docker_build_gather_facts
      delegate_to: "{{ groups['docker_build_hosts'] | first }}"
      when: not skip_build_and_push

    - role: docker_image_build
      delegate_to: "{{ groups['docker_build_hosts'] | first }}"
      when: not skip_build_and_push
