- hosts: docker_build_images
  # playbooks gather facts before roles, which is where delegation is performed
  # so set gather_facts to no here, and run setup explicitly in the role
  gather_facts: no
  roles:
    - role: docker_build_gather_facts
      delegate_to: "{{ groups['docker_build_hosts'] | first }}"

    - role: docker_image_build
      delegate_to: "{{ groups['docker_build_hosts'] | first }}"
      when: "'build' in tags"
