- hosts: docker_services
  # playbooks gather facts before roles, which is where delegation is performed
  # so set gather_facts to no here, and run setup explicitly in the role
  gather_facts: no
  roles:
    - role: docker_service_build
      delegate_to: "{{ groups['docker_build_hosts'] | first }}"
      when: "'build_image' in hostvars[inventory_hostname]"
