- hosts: docker_build_images
  # nothing here should rely on gathered facts
  gather_facts: no
  roles:
    - role: docker_skip_hosts_in_registry
      delegate_to: "{{ groups['docker_build_hosts'] | first }}"
      tags:
        - never
        - skip-if-in-registry

    - role: docker_image_push
      delegate_to: "{{ groups['docker_build_hosts'] | first }}"
      when: not skip_build_and_push
