- name: Log in to repositories
  docker_login:
    registry: "{{ registry }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
  become: yes
  loop: "{{ groups['docker_nodes'] }}"
  delegate_to: "{{ item }}"
