- name: "{{ stage_item.src }} find path components to template"
  # path components exist on the host running ansible, which isn't always the host doing the docker build
  delegate_to: localhost
  find:
    file_type: any
    recurse: true
    hidden: yes
    paths:
      - "{{ stage_item.src }}"
    patterns: "{{ stage_item.pattern | default(omit) }}"
  register: template_path_components

- name: "{{ stage_item.src }} create template directories"
  file:
    path: "{{ stage_dest }}/{{ item.path | relpath(stage_item.src) }}"
    state: directory
    mode: "{{ stage_item.directory_mode | default(omit) }}"
  loop: "{{ template_path_components.files }}"
  when: item.isdir

- name: "{{ stage_item.src }} template files"
  template:
    src: "{{ item.path }}"
    dest: "{{ stage_dest }}/{{ item.path | relpath(stage_item.src) }}"
    mode: "{{ stage_item.mode | default(omit) }}"
  loop: "{{ template_path_components.files }}"
  when: not item.isdir and not item.islnk
