docker_build_directory_prefix: docker_build_
indexed_field_stanza_prefix: docker_build_
indexed_field_class_name: docker_build

apt_packages: "{{ common_apt_packages + host_apt_packages }}"

indexed_fields: "{{ common_indexed_fields | combine(host_indexed_fields) }}"
