- name: validate src or content presence
  assert:
    that:
      - src is defined or content is defined

- name: "{{ src }} get stat"
  delegate_to: localhost
  stat:
    path: "{{ src }}"
  register: copy_src_stat
  when: src is defined

# we have to use a variable name not passed to this tasks file if we want to override it
- name: "{{ src }} set copy_src"
  set_fact:
    copy_src: "{{ src }}"
  when: src is defined

# append / to copy_src if it's a directory, to copy only its contents, which is how the templating works as well
- name: "{{ src }} add trailing slash to src if it's a directory"
  set_fact:
    copy_src: "{{ copy_src }}/"
  when: src is defined and copy_src_stat.stat.isdir

- name: "{{ src }} copy files"
  copy:
    src: "{{ copy_src | default(omit) }}"
    content: "{% if content is defined %}{{ content | string }}{% else %}{{ omit }}{% endif %}"
    dest: "{{ dest }}"
    mode: "{{ mode | default(omit) }}"
    directory_mode: "{{ directory_mode | default(omit) }}"
