- include_tasks: swarm_firewall_ports.yml

- include_tasks: existing_join_tokens.yml

- when: "('docker_swarm_managers' in group_names) and (manager_join_token is not defined)"
  include_tasks: new_swarm.yml

- include_tasks: existing_join_tokens.yml

- include_tasks: join_swarm.yml
