- name: bring up first swarm member
  docker_swarm:
    state: present
  become: true
  run_once: true
  register: new_swarm_info

- name: Set join tokens from new swarm
  set_fact:
    manager_join_token: "{{ new_swarm_info.swarm_facts.JoinTokens.Manager }}"
    worker_join_token: "{{ new_swarm_info.swarm_facts.JoinTokens.Worker }}"
  when: >
    (manager_join_token is not defined)
