# - name: install docker packages
#   package:
#     name: "{{ item }}"
#     state: present
#   become: true
#   register: docker_install_results
#   loop:
#     - "{{ containerd_io_package }}"
- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - firewalld
      - python3-firewall
    state: present
    update_cache: yes
  become: true

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.asc
  become: true

- name: Set permissions on GPG key
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    register: docker_install_results
  become: true

- name: flag docker service for restart if any changes to installed packages
  set_fact:
    docker_service_state: restarted
  loop: "{{ docker_install_results.results }}"
  when: item.changed

# this will make use of the docker_service_state value set above
# this will always get run to at least ensure the service is enabled/started, but will
# also restart the service if any chnages to the packages were made
- include_tasks: docker-enable-start-restart.yml

- name: make sure docker is running
  include_tasks: docker-daemon-running.yml

- name: install /etc/docker/daemon.json
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  become: true
  register: docker_daemon_json_result

# this could be done via a handler, but since it would only be used once not bothering
- include_tasks: docker-enable-start-restart.yml
  vars:
    docker_service_state: restarted
  when: docker_daemon_json_result.changed

- name: make sure docker is running
  include_tasks: docker-daemon-running.yml
