- name: Include OS-specific Docker tasks
  include_tasks: "{{ 'docker-centos.yml' if ansible_distribution == 'CentOS' else 'docker-ubuntu.yml' }}"
  when: "'docker_swarm_managers' in group_names or 'docker_swarm_workers' in group_names"
