- name: Set OS-specific Docker task file
  set_fact:
    docker_task_file: "{{ 'docker-centos.yml' if ansible_distribution == 'CentOS' else 'docker-ubuntu.yml' }}"

- name: Include OS-specific Docker tasks
  include_tasks: "{{ docker_task_file }}"
