- name: create copy paths
  file:
    path: "{{ docker_build_directory.path }}/{{ item.key }}"
    state: directory
  loop: "{{ copy_paths | dict2items }}"
  when: "not ('is_base_path' in item.value and item.value.is_base_path)"

- include_tasks: stage_type.yml
  vars:
    type_task_file: "{{ stage_type_item.task_file }}"
    type_loop_var: "{{ stage_type_item.task_loop_var }}"
  loop:
    - task_file: stage_template_path.yml
      task_loop_var: "{{ template_paths }}"
    - task_file: stage_copy_path.yml
      task_loop_var: "{{ copies }}"
    - task_file: stage_archive_path.yml
      task_loop_var: "{{ archives }}"
  loop_control:
    loop_var: stage_type_item
