- name: create staging paths
  file:
    path: "{{ docker_build_directory.path }}/{{ item.key }}"
    state: directory
  loop: "{{ staging_paths | dict2items }}"
  when: "not ('is_base_path' in item.value and item.value.is_base_path)"

- include_tasks: "stage_{{ stage_item.type }}.yml"
  vars:
    stage_item_config: "{{ stage_item }}"
  loop: "{{ stage_items }}"
  loop_control:
    loop_var: stage_item
