- name: create apps work directory
  file:
    path: "{{ docker_build_directory.path }}/apps"
    state: directory

- name: find app components to template
  # app components exist on the host running ansible, which isn't always the host doing the docker build
  delegate_to: localhost
  find:
    file_type: any
    recurse: true
    paths:
      - "{{ role_path }}/templates/auto"
  register: app_components

- name: create app directories
  file:
    path: "{{ docker_build_directory.path }}/{{ item.path | relpath(role_path + '/templates/auto') }}"
    state: directory
  loop: "{{ app_components.files }}"
  when: item.isdir

- name: template app files
  template:
    src: "{{ item.path }}"
    dest: "{{ docker_build_directory.path }}/{{ item.path | relpath(role_path + '/templates/auto') }}"
    mode: preserve
  loop: "{{ app_components.files }}"
  when: not item.isdir and not item.islnk
