- include_tasks: template_path.yml
  vars:
    template_path: "{{ role_path }}/templates/auto"

- include_tasks: template_path.yml
  vars:
    template_path: "{{ role_path }}/templates/manual/production"
  when: production_image

- include_tasks: template_path.yml
  vars:
    template_path: "{{ role_path }}/templates/manual/kvstore_disabled"
  when: kvstore_disabled
