- include_tasks: template_path.yml
  vars:
    template_path: "{{ template_path_item.template_path }}"
  when: template_path_item.condition
  loop:
    - template_path: "{{ role_path }}/templates/auto"
      condition: "{{ true }}"

    - template_path: "{{ role_path }}/templates/manual/production"
      condition: "{{ production_image }}"

    - template_path: "{{ role_path }}/templates/manual/kvstore_disable"
      condition: "{{ kvstore_disabled }}"

  loop_control:
    loop_var: template_path_item
