- include_tasks: template_path.yml
  vars:
    src: "{{ template_path_item.src }}"
    owner: "{{ template_path_item.owner | default(omit) }}"
    group: "{{ template_path_item.group | default(omit) }}"
    name: "{{ template_path_item.name }}"
  when: template_path_item.condition
  loop: "{{ template_paths }}"
  loop_control:
    loop_var: template_path_item
