# test templating a directory structure
# src *must* be a directory
src: "hosts/{{ inventory_hostname }}/templates"
# but you can specify patterns if you want specific files
pattern:
  - single_file.txt
dest: "template_test_output"
