- name: "create {% if intermediate_configs is defined and intermediate_configs %}intermediate {% endif %}docker configs"
  docker_config:
    # pipe to the string filter here, which is as late as possible, to prevent ansible from interpreting content as yaml or json
    data: "{{ item.content | string }}"
    data_is_b64: "{{ item.content_is_b64 | default(omit) }}"
    name: "{% if intermediate_configs is defined and intermediate_configs %}{{ item.content | to_uuid }}{% else %}{{ item.name }}{% endif %}"
  loop: "{{ docker_configs }}"
  when: item is default_or_present
  become: "{{ docker_become_user is defined }}"
  become_user: "{{ docker_become_user|default(omit) }}"
